---
title: "Figure 5 and associated supplementary figures"
output: html_notebook
author: Grace Avecilla
---

```{r}
library(tidyverse)
library(patchwork)
library(scales)
library(ggbeeswarm)
library(reticulate)
theme_set(theme_classic(base_size = 21))

param_dir = "/Volumes/GoogleDrive/.shortcut-targets-by-id/19NQRq-XLPpjqJGmLbP4MHRjala2WVahk/Avecilla et al Simulating CNV evolution/scripts/cnv_sims_inference/hpc_output/Lauer2018/single/param_estimates/"
posterior_dir = "/Volumes/GoogleDrive/.shortcut-targets-by-id/19NQRq-XLPpjqJGmLbP4MHRjala2WVahk/Avecilla et al Simulating CNV evolution/scripts/cnv_sims_inference/hpc_output/Lauer2018/single/posteriors/"
fig_path = "/Volumes/GoogleDrive/.shortcut-targets-by-id/19NQRq-XLPpjqJGmLbP4MHRjala2WVahk/Avecilla et al Simulating CNV evolution/scripts/cnv_sims_inference/figs/"
```

```{r}
read_est_params = function(x) {
  if(str_detect(x, "NPE")==TRUE){
    file = read_csv(x, col_names = c("Model","Method","col_to_sep","col_to_sep2",
                                     "mu_est","s_snv","m_snv","rmse_map",
                                     "mean_rmse_ppc","rmse95_low_ppc","rmse95_hi_ppc",
                                     "corr_map",
                                     "mean_corr_ppc","corr95_low_ppc", "corr95_hi_ppc",
                                     "fit_95hdi_low","fit_95hdi_high",
                                     "mut_95hdi_low","mut_95hdi_high",
                                     "aic", "dic", "waic1", "waic2"),
                    col_types = cols()) %>%
      separate(col_to_sep, into = c(NA,NA,NA,"n_presim", "presim_rep"), 
               sep="([_.])") %>%
      separate(col_to_sep2, into = c("Population", "s_est"), 
               sep="([-])") %>%
      mutate(s_est_10 = as.numeric(s_est)*-1,
             mu_est_10 = mu_est,
             s_est = 10^(as.numeric(s_est)*-1),
             mu_est = 10^mu_est) %>%
      mutate(flow_type = if_else(str_detect(x, "nsf"), "NSF", "MAF"))
  }
  if(str_detect(x, "ABC")==TRUE) {
    file = read_csv(x, col_names = c("Model","Method","n_presim","col_to_sep",
                                    "mu_est","s_snv","m_snv","rmse_map",
                                     "mean_rmse_ppc","rmse95_low_ppc","rmse95_hi_ppc",
                                     "corr_map",
                                     "mean_corr_ppc","corr95_low_ppc", "corr95_hi_ppc",
                                     "fit_95hdi_low","fit_95hdi_high",
                                     "mut_95hdi_low","mut_95hdi_high",
                                     "aic", "dic", "waic1", "waic2"),
                    col_types = cols()) %>%
      separate(col_to_sep, into = c("Population", "s_est"), 
               sep="([-])") %>%
      mutate(presim_rep = case_when(str_detect(x, "_1_") ~ "1",
                                    str_detect(x, "_2_") ~ "2",
                                    str_detect(x, "_3_") ~ "3")) %>%
      mutate(s_est_10 = as.numeric(s_est)*-1,
             mu_est_10 = mu_est, 
             s_est = 10^(as.numeric(s_est)*-1),
             mu_est = 10^mu_est) %>%
      select("Model","Method","n_presim", "presim_rep","Population",
             "s_est","mu_est","s_snv","m_snv","rmse_map",
             "mean_rmse_ppc","rmse95_low_ppc","rmse95_hi_ppc",
             "corr_map",
             "mean_corr_ppc","corr95_low_ppc", "corr95_hi_ppc",
             "fit_95hdi_low","fit_95hdi_high",
             "mut_95hdi_low","mut_95hdi_high",
             "aic", "dic", "waic1", "waic2", "s_est_10", "mu_est_10") %>%
      mutate(flow_type = NA) %>%
      mutate(n_presim = if_else(n_presim == 100, "10000", "100000"))
  }
  return(file)
}
```

```{r}
read_posterior_NPE = function(x,d){
  t=unlist(str_split(x, "_"))
  if(str_detect(x, "nsf")) {
    data = read_csv(paste0(d,x), col_names = c("s_est","mu_est"), col_types = cols()) %>%
      mutate(Model = t[2], Method = t[3], n_presim = t[5], presim_rep = str_sub(t[6], end=1)) %>%
      mutate(flow_type = "NSF") %>%
      mutate(generations = if_else(str_detect(x, "116"),116,267)) %>%
      mutate(Population = if_else(str_detect(x,"gln"), 
                                  paste(str_sub(t[6], 2), t[7], sep = "_"), str_sub(t[6], 2))) %>%
      mutate(s_est_10 = s_est,
             mu_est_10 = mu_est,
             s_est = 10^s_est,
             mu_est = 10^mu_est)
  } else {
    data = read_csv(paste0(d,x), col_names = c("s_est","mu_est"), col_types = cols()) %>%
      mutate(Model = t[2], Method = t[3], n_presim = t[4], presim_rep = str_sub(t[6], end=1)) %>%
      mutate(flow_type = "MAF") %>%
      mutate(generations = if_else(str_detect(x, "116"),116,267)) %>%
      mutate(Population = if_else(str_detect(x,"gln"), 
                                  paste(str_sub(t[6], 2), t[7], sep = "_"), str_sub(t[6], 2))) %>%
      mutate(s_est_10 = s_est,
             mu_est_10 = mu_est,
             s_est = 10^s_est,
             mu_est = 10^mu_est)
  }
}
```


```{r}
param_files = list.files(path = param_dir, pattern = '*est_real_params.csv')
param_files = paste0(param_dir, param_files)

param_list = map(param_files,read_est_params)

param_all = do.call(rbind, param_list)

param_long = param_all %>% 
  pivot_longer(cols = c(mu_est,s_est), names_to = "parameter",
               values_to = "value") 

param_files = list.files(path = "/Volumes/GoogleDrive/.shortcut-targets-by-id/19NQRq-XLPpjqJGmLbP4MHRjala2WVahk/Avecilla et al Simulating CNV evolution/scripts/cnv_sims_inference/hpc_output/Lauer2018/single116/param_estimates/", pattern = '*est_real_params.csv')
param_files = paste0("/Volumes/GoogleDrive/.shortcut-targets-by-id/19NQRq-XLPpjqJGmLbP4MHRjala2WVahk/Avecilla et al Simulating CNV evolution/scripts/cnv_sims_inference/hpc_output/Lauer2018/single116/param_estimates/", param_files)

param_list = map(param_files,read_est_params)

param_116 = do.call(rbind, param_list) %>% mutate(gen = 116)

param_all = param_all %>%
  mutate(gen = 267) %>%
  #filter(presim_rep != 1) %>%
  bind_rows(param_116) 
```

```{r}
post_files = list.files(path = posterior_dir, pattern = '*NPE_posterior_samples.csv')

post_list = map(post_files,read_posterior_NPE,d=posterior_dir)
post_all = do.call(rbind, post_list)

post_files = list.files(path = "/Volumes/GoogleDrive/.shortcut-targets-by-id/19NQRq-XLPpjqJGmLbP4MHRjala2WVahk/Avecilla et al Simulating CNV evolution/scripts/cnv_sims_inference/hpc_output/Lauer2018/single116/posteriors/", pattern = '*NPE_posterior_samples.csv')

post_list = map(post_files,read_posterior_NPE,d="/Volumes/GoogleDrive/.shortcut-targets-by-id/19NQRq-XLPpjqJGmLbP4MHRjala2WVahk/Avecilla et al Simulating CNV evolution/scripts/cnv_sims_inference/hpc_output/Lauer2018/single116/posteriors/")
post_all = post_all %>%
  bind_rows(do.call(rbind, post_list))
```

```{r}
observations_wide = read_csv("/Volumes/GoogleDrive/.shortcut-targets-by-id/19NQRq-XLPpjqJGmLbP4MHRjala2WVahk/Avecilla et al Simulating CNV evolution/scripts/cnv_sims_inference/hpc/new/PopPropForABC_all.csv") 

observations = observations_wide %>%
  bind_cols(read_csv("/Volumes/GoogleDrive/.shortcut-targets-by-id/19NQRq-XLPpjqJGmLbP4MHRjala2WVahk/Avecilla et al Simulating CNV evolution/scripts/cnv_sims_inference/hpc/generations.csv")) %>%
  pivot_longer(-Generation,
               names_to = "Population",
               values_to = "prop_CNV") %>%
  mutate(type = "Observation")
```


```{r}
mycolors = c("bc01"="#a6cee3",
             "bc02"="#1f78b4",
             "gln_01"="#b2df8a",
             "gln_02"="#33a02c",
             "gln_03"="#fb9a99",
             "gln_04"="#e31a1c",
             "gln_05"="#fdbf6f",
             "gln_06"="#ff7f00",
             "gln_07"="#cab2d6",
             "gln_08"="#6a3d9a",
             "gln_09"="#ffff99")
param_data = param_all %>% 
  filter(Method=="NPE") %>%
  filter(flow_type == "NSF") %>%
  filter(n_presim == "100000") %>%
  filter(s_snv == 0.001 & m_snv == 1e-5)

param_data %>%
  filter(gen == 116) %>%
  group_by(Model, Method, flow_type, n_presim) %>%
  summarize(mean_s = mean(s_est), mean_mu = mean(mu_est),
            med_s = median(s_est), med_mu = median(mu_est), 
            min_s = min(s_est), max_s = max(s_est), 
            min_mu = min(mu_est_10), max_mu = max(mu_est_10))
```

```{r a WF inference plot}
a5 = param_data %>% 
  filter(Model == "WF") %>%
  filter(gen == 116) %>%
  ggplot(aes(mu_est_10, s_est, color = Population, shape=as.factor(presim_rep))) +
  geom_point(aes(fill=Population),size = 3, alpha = 0.5) +
  geom_errorbar(aes(ymin = 10^fit_95hdi_low,ymax = 10^fit_95hdi_high)) + 
  geom_errorbarh(aes(xmin = mut_95hdi_low,xmax = mut_95hdi_high)) +
  ylab("MAP s") +
  xlab(expression(paste("log10(MAP ", delta,")"))) + 
  #facet_grid(gen~Model) + 
  scale_color_manual(values=mycolors, name = "Population") +
  scale_fill_manual(values=mycolors, name="Population") + 
  scale_shape_manual(values = c(21, 22, 23), name = "Inference set") +
  theme(legend.position = "none") +
  ggtitle("WF")
a5
```

```{r b Chemo inference plot}
b5 = param_data %>% 
  filter(Model == "Chemo") %>%
  filter(gen == 116) %>%
  ggplot(aes(mu_est_10, s_est, color = Population, shape=as.factor(presim_rep))) +
  geom_point(aes(fill=Population), size = 3, alpha = 0.5) +
  geom_errorbar(aes(ymin = 10^fit_95hdi_low,ymax = 10^fit_95hdi_high)) + 
  geom_errorbarh(aes(xmin = mut_95hdi_low,xmax = mut_95hdi_high)) +
  ylab("MAP s") +
  xlab(expression(paste("log10(MAP ", delta,")"))) + 
  #facet_grid(gen~Model) + 
  scale_color_manual(values=mycolors, name = "Population") +
  scale_fill_manual(values=mycolors, name="Population") + 
  scale_shape_manual(values = c(21, 22, 23), name = "Inference set") + 
  theme(legend.position = "none") +
  ggtitle("Chemo")
b5
```

```{r c RMSE plot}
c5 = param_data %>%
  filter(gen == 116) %>%
  ggplot(aes(Model, mean_rmse_ppc, color=Population,fill=Population, shape=as.factor(presim_rep))) +
  geom_pointrange(aes(ymin = rmse95_low_ppc,ymax = rmse95_hi_ppc), alpha=0.5,
                  position=position_dodge2(width=0.75)) +
  ylab("Posterior predictive\naccuracy (RMSE)") +
  xlab("") +
  scale_color_manual(values=mycolors, name = "Population") +
  scale_shape_manual(values = c(21, 22, 23), name = "Inference set") +
  scale_fill_manual(values=mycolors, name="Population") +
  theme(legend.position = "none")
c5
```


```{r set up for ppc}
param_chemo = param_data %>% filter(Model == "Chemo")
param_wf = param_data %>% filter(Model =="WF")
obs_wide = observa
```

```{python}
from cnv_simulation import CNVsimulator_simpleWF, CNVsimulator_simpleChemo
import numpy as np

def rmse(a, b):
    return ((a-b)**2).mean()**0.5

N = 3.3e8
s_snv=0.001
m_snv=1e-5
reps=1
generation=np.genfromtxt("/Volumes/GoogleDrive/.shortcut-targets-by-id/19NQRq-XLPpjqJGmLbP4MHRjala2WVahk/Avecilla et al Simulating CNV evolution/scripts/cnv_sims_inference/hpc/generations.csv",delimiter=',', skip_header=1,dtype="int64")

ppc_wf = []
for i in range(r.param_wf.shape[0]):
  cnv_params = np.array([r.param_wf['s_est_10'][i],r.param_wf['mu_est_10'][i]])
  obs_post = CNVsimulator_simpleWF(reps = reps, N=N, s_snv=s_snv, m_snv=m_snv, generation=generation, seed=None, parameters=cnv_params)
  ppc_wf.append(obs_post)
ppc_wf=np.vstack(ppc_wf)

ppc_chemo = []
for i in range(r.param_chemo.shape[0]):
  cnv_params = np.array([r.param_chemo['s_est_10'][i],r.param_chemo['mu_est_10'][i]])
  obs_post = CNVsimulator_simpleChemo(reps, s_snv, m_snv, generation, parameters=cnv_params, seed=None)
  ppc_chemo.append(obs_post)
ppc_chemo=np.vstack(ppc_chemo)
```

```{python}
import pandas as pd
rmse_wf = []
for i in range(ppc_wf.shape[0]):
  rmse_wf_267=rmse(ppc_wf[i,:],r.observations_wide[r.param_wf['Population'][i]].to_numpy())
  rmse_wf_116=rmse(ppc_wf[i,0:11],r.observations_wide[r.param_wf['Population'][i]].to_numpy()[0:11])
  rmse_wf.append([rmse_wf_267, rmse_wf_116])

rmse_chemo = []
for i in range(ppc_chemo.shape[0]):
  rmse_chemo_267=rmse(ppc_chemo[i,:],r.observations_wide[r.param_chemo['Population'][i]].to_numpy())
  rmse_chemo_116=rmse(ppc_chemo[i,0:11],r.observations_wide[r.param_chemo['Population'][i]].to_numpy()[0:11])
  rmse_chemo.append([rmse_chemo_267, rmse_chemo_116])


ppc_wf_all = pd.concat([pd.DataFrame(ppc_wf, columns = generation.tolist()), r.param_wf], axis=1)
ppc_chemo_all = pd.concat([pd.DataFrame(ppc_chemo, columns = generation.tolist()), r.param_chemo], axis=1)

ppc_wf_all = pd.concat([ppc_wf_all, pd.DataFrame(rmse_wf, columns = ['map_rmse_267','map_rmse_116'])], axis=1)
ppc_chemo_all = pd.concat([ppc_chemo_all, pd.DataFrame(rmse_chemo, columns = ['map_rmse_267','map_rmse_116'])], axis=1)

```

```{r d PPCs plot}
d5 = py$ppc_chemo_all %>%
  as_tibble() %>%
  bind_rows(py$ppc_wf_all) %>%
  filter(gen ==  116) %>%
  filter(presim_rep == 1) %>%
  pivot_longer(cols = `25`:`267`, names_to = "generation", values_to = "prop_CNV") %>%
  mutate(type = case_when(Model == "Chemo"~"Chemo PPC", 
                          Model == "WF" ~"WF PPC")) %>%
  mutate(Generation = as.numeric(generation)) %>%
  select(Generation, Population, prop_CNV, type) %>%
  bind_rows(observations) %>% #%>% filter(Generation <= 116)) %>%
  #filter(Population %in% c("gln_07")) %>% #"bc01", "bc02","gln_01", "gln_06", "gln_08" #"gln_07"
  ggplot(aes(Generation, prop_CNV, color = Population)) +
  geom_line(aes(linetype = type), size=1.5, alpha = 0.7) +
  facet_wrap(~Population) +
  scale_linetype_manual(values = c("solid", "dotted", "longdash"),
                     breaks = c("Observation", "WF PPC","Chemo PPC"), name = "") +
  scale_color_manual(values=mycolors) +
  ylab("Proportion of cells with GAP1 CNV") +
  #geom_point(data=param_data,aes(x=mean_rmse_ppc, y=mean_rmse_ppc, shape=as.factor(presim_rep)),alpha = 0) +
  guides(shape = guide_legend(override.aes = list(alpha = 1)), linetype=guide_legend(keywidth = 3, keyheight = 1))
d5
```

```{r}
layout <- "
AADDDD
BBDDDD
CCDDDD
"
fig5 = a5 + b5 + c5 + d5 + plot_annotation(tag_levels = 'A') + plot_layout(design = layout)
fig5
ggsave(paste0(fig_path,"Figure5.pdf"), plot = fig5, width = 22, height = 12, units = "in")
ggsave(paste0(fig_path,"Figure5.png"), plot = fig5, width = 22, height = 12, units = "in")
```



```{r sup fig 8}
sup = py$ppc_chemo_all %>%
  as_tibble() %>%
  bind_rows(py$ppc_wf_all) %>%
  filter(presim_rep == "1") %>%
  pivot_longer(cols = `25`:`267`, names_to = "generation", values_to = "prop_CNV") %>%
  mutate(type = case_when(Model == "Chemo" & gen == 116~"Chemo ppc 116", 
                          Model == "Chemo" & gen == 267~"Chemo ppc 267",
                          Model == "WF" & gen == 116~"WF ppc 116",
                          Model == "WF" & gen == 267~"WF ppc 267")) %>%
  mutate(Generation = as.numeric(generation)) %>%
  select(Generation, Population, prop_CNV, type, presim_rep) %>%
  bind_rows(observations) %>%
  ggplot(aes(Generation, prop_CNV, color = type, fill = presim_rep)) +
  geom_line(size=1.5, alpha = 0.7) + #aes(linetype = type)
  facet_wrap(~Population) +
  scale_color_manual(values = c("black", "lightblue", "darkblue", "green", "darkgreen"),
                     breaks = c("Observation", "WF ppc 116","WF ppc 267", "Chemo ppc 116","Chemo ppc 267")) +
  ylab("Proportion of cells with GAP1 CNV") 
sup
ggsave(paste0(fig_path,"SupplementaryFigure8.pdf"), plot = sup, width = 25, height = 15, units = "in")
ggsave(paste0(fig_path,"SupplementaryFigure8.png"), plot = sup, width = 25, height = 15, units = "in")
```


```{r sup fig 9}
as_tibble(py$ppc_wf_all) %>%
  bind_rows(py$ppc_chemo_all) %>%
  filter(n_presim == "100000") %>%
  select(Model, Method, Population, gen, map_rmse_267, map_rmse_116) %>%
  group_by(gen) %>%
  summarize(mean_map_rmse_267 = mean(map_rmse_267), mean_map_rmse_116 = mean(map_rmse_116)) %>%
  knitr::kable()

sup = as_tibble(py$ppc_wf_all) %>%
  bind_rows(py$ppc_chemo_all) %>%
  filter(n_presim == "100000") %>%
  select(Model, Method, Population, gen, map_rmse_267, map_rmse_116) %>%
  mutate(gen_lab = if_else(gen == 116, "Inference using up\nto generation 116","Inference using up\nto generation 267")) %>%
  pivot_longer(cols = c("map_rmse_267", "map_rmse_116"), names_to = "type", values_to = "value") %>%
  ggplot(aes(type, value, color = Population)) +
  scale_color_manual(values=mycolors) +
  geom_beeswarm(dodge.width = 0.5) +
  scale_x_discrete(labels = c("PPC up to\ngeneration 116", "PPC up to\ngeneration 267"), name="") +
  facet_grid(Model~gen_lab) +
  ylab("MAP RMSE")

sup
ggsave(paste0(fig_path,"SupplementaryFigure9.pdf"), plot = sup, width = 12, height = 6, units = "in")
ggsave(paste0(fig_path,"SupplementaryFigure9.png"), plot = sup, width = 12, height = 6, units = "in")
```

```{r sup fig 10}
a = param_data %>% 
  filter(Model == "WF") %>%
  #filter(gen == 267) %>%
  ggplot(aes(mu_est_10, s_est, color = Population, shape=as.factor(presim_rep))) +
  geom_point(aes(fill=Population), size = 3, alpha = 0.5) +
  geom_errorbar(aes(ymin = 10^fit_95hdi_low,ymax = 10^fit_95hdi_high)) + 
  geom_errorbarh(aes(xmin = mut_95hdi_low,xmax = mut_95hdi_high)) +
  ylab("MAP s") +
  xlab(expression(paste("log10(MAP ", delta,")"))) + 
  facet_wrap(~gen) +
  scale_color_manual(values=mycolors, name = "Population") +
  scale_fill_manual(values=mycolors, name="Population") + 
  scale_shape_manual(values = c(21, 22, 23), name = "Inference set") + 
  theme(legend.position = "none") +
  ggtitle("WF")

b = param_data %>% 
  filter(Model == "Chemo") %>%
  #filter(gen == 267) %>%
  ggplot(aes(mu_est_10, s_est, color = Population, shape=as.factor(presim_rep))) +
  geom_point(aes(fill=Population), size = 3, alpha = 0.5) +
  geom_errorbar(aes(ymin = 10^fit_95hdi_low,ymax = 10^fit_95hdi_high)) + 
  geom_errorbarh(aes(xmin = mut_95hdi_low,xmax = mut_95hdi_high)) +
  ylab("MAP s") +
  xlab(expression(paste("log10(MAP ", delta,")"))) + 
  facet_wrap(~gen) + 
  scale_color_manual(values=mycolors, name = "Population") +
  scale_fill_manual(values=mycolors, name="Population") + 
  scale_shape_manual(values = c(21, 22, 23), name = "Training set") + 
  #theme(legend.position = "none") +
  ggtitle("Chemo")

sup = a / b + plot_annotation(tag_levels = 'A') 
sup
ggsave(paste0(fig_path,"SupplementaryFigure10.pdf"), plot = sup, width = 12, height = 12, units = "in")
ggsave(paste0(fig_path,"SupplementaryFigure10.png"), plot = sup, width = 12, height = 12, units = "in")
```


```{r sup fig 11}
data = param_116 %>%
  filter(Model == "WF") %>%
  filter(Method=="NPE") %>%
  filter(flow_type == "NSF") %>%
  filter(n_presim == "100000" & presim_rep == "1") %>%
  unite(other_params, c("s_snv", "m_snv"), remove = F) %>%
  filter(other_params !=  "0.1_0") %>%
  filter(other_params !=  "0.01_0")


labels = c("0.001_1e-05" = expression(atop("s = 0.001,", paste(delta, "  = 1e-5"))),
                                                  "0_0"  = expression(atop("s = 0,", paste(delta, "  = 0"))),
                                                  "0.01_1e-05"  = expression(atop("s = 0.01,", paste(delta, "  = 1e-5"))),
                                                  "0.1_1e-05"  = expression(atop("s = 0.1,", paste(delta, "  = 1e-5"))),
                                                  "0.1_1e-07"  = expression(atop("s = 0.1,", paste(delta, "  = 1e-7"))))
sup = data %>%
  ggplot(aes(mu_est_10, s_est, color = other_params)) +
  geom_point(aes(fill=other_params),size = 3, alpha = 0.5) +
  geom_errorbar(aes(ymin = 10^fit_95hdi_low,ymax = 10^fit_95hdi_high)) + 
  geom_errorbarh(aes(xmin = mut_95hdi_low,xmax = mut_95hdi_high)) +
  ylab("MAP s") +
  xlab(expression(paste("log10(MAP ", delta,")"))) + 
  facet_wrap(~Population) +
  scale_color_discrete(labels = labels,  name = "Other beneficial mutations") +
  scale_fill_discrete(guide = "none") +
  theme(legend.position = 'top')
sup
ggsave(paste0(fig_path,"SupplementaryFigure11.pdf"), plot = sup, width = 13, height = 12, units = "in")
ggsave(paste0(fig_path,"SupplementaryFigure11.png"), plot = sup, width = 13, height = 12, units = "in")
```

```{r sup fig 12}
a = data %>%
  ggplot(aes(Population, mean_rmse_ppc, color=other_params)) +
  geom_pointrange(aes(ymin = rmse95_low_ppc,ymax = rmse95_hi_ppc), alpha=0.5,
                  position=position_dodge2(width=0.5)) +
  ylab("Posterior predictive check\nroot mean square error") +
  xlab("") +
  scale_color_discrete(labels = labels,  name = "Other beneficial mutations") +
  theme(legend.position = 'bottom')

b = data %>%
  ggplot(aes(Population, mean_corr_ppc, color=other_params)) +
  geom_pointrange(aes(ymin = rmse95_low_ppc,ymax = rmse95_hi_ppc), alpha=0.5,
                  position=position_dodge2(width=0.5)) +
  ylab("Posterior predictive check\ncorrelation") +
  scale_color_discrete(labels = labels,  name = "Other beneficial mutations") +
  xlab("") +
  theme(legend.position = "none") 

sup = a / b + plot_annotation(tag_levels = 'A') 
sup
ggsave(paste0(fig_path,"SupplementaryFigure12.pdf"), plot = sup, width = 12, height = 12, units = "in")
ggsave(paste0(fig_path,"SupplementaryFigure12.png"), plot = sup, width = 12, height = 12, units = "in")
```

